spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rbac_db
    username: postgres
    password: V_SPratheep06
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

jwt:
  secret: myJwtSecretKeyThatIsVeryLongAndSecureForProductionUse123456789
  expirationMs: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    com.example.rbacsystem: DEBUG